package shordinger.ModWrapper.migration.wrapper.minecraft.init;

import java.util.Set;

import javax.annotation.Nullable;

import net.minecraft.block.BlockBeacon;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockCactus;
import net.minecraft.block.BlockCauldron;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockDaylightDetector;
import net.minecraft.block.BlockDeadBush;
import net.minecraft.block.BlockDoor;
import net.minecraft.block.BlockDoublePlant;
import net.minecraft.block.BlockDynamicLiquid;
import net.minecraft.block.BlockFire;
import net.minecraft.block.BlockFlower;
import net.minecraft.block.BlockGrass;
import net.minecraft.block.BlockHopper;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockPistonBase;
import net.minecraft.block.BlockPistonExtension;
import net.minecraft.block.BlockPistonMoving;
import net.minecraft.block.BlockPortal;
import net.minecraft.block.BlockRedstoneComparator;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.block.BlockRedstoneWire;
import net.minecraft.block.BlockReed;
import net.minecraft.block.BlockSand;
import net.minecraft.block.BlockSkull;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStainedGlass;
import net.minecraft.block.BlockStainedGlassPane;
import net.minecraft.block.BlockStaticLiquid;
import net.minecraft.block.BlockTallGrass;
import net.minecraft.block.BlockTripWireHook;
import net.minecraft.init.Blocks;
import net.minecraft.util.ResourceLocation;

import com.google.common.collect.Sets;

import shordinger.ModWrapper.migration.wrapper.minecraft.block.WrapperBlock;

public class WrapperBlocks extends Blocks {

    private static final Set<WrapperBlock> CACHE;
    public static final WrapperBlock AIR;
    public static final WrapperBlock STONE;
    public static final BlockGrass GRASS;
    public static final WrapperBlock DIRT;
    public static final WrapperBlock COBBLESTONE;
    public static final WrapperBlock PLANKS;
    public static final WrapperBlock SAPLING;
    public static final WrapperBlock BEDROCK;
    public static final BlockDynamicLiquid FLOWING_WATER;
    public static final BlockStaticLiquid WATER;
    public static final BlockDynamicLiquid FLOWING_LAVA;
    public static final BlockStaticLiquid LAVA;
    public static final BlockSand SAND;
    public static final WrapperBlock GRAVEL;
    public static final WrapperBlock GOLD_ORE;
    public static final WrapperBlock IRON_ORE;
    public static final WrapperBlock COAL_ORE;
    public static final WrapperBlock LOG;
    public static final WrapperBlock LOG2;
    public static final BlockLeaves LEAVES;
    public static final BlockLeaves LEAVES2;
    public static final WrapperBlock SPONGE;
    public static final WrapperBlock GLASS;
    public static final WrapperBlock LAPIS_ORE;
    public static final WrapperBlock LAPIS_WRAPPER_BLOCK;
    public static final WrapperBlock DISPENSER;
    public static final WrapperBlock SANDSTONE;
    public static final WrapperBlock NOTEBLOCK;
    public static final WrapperBlock BED;
    public static final WrapperBlock GOLDEN_RAIL;
    public static final WrapperBlock DETECTOR_RAIL;
    public static final BlockPistonBase STICKY_PISTON;
    public static final WrapperBlock WEB;
    public static final BlockTallGrass TALLGRASS;
    public static final BlockDeadBush DEADBUSH;
    public static final BlockPistonBase PISTON;
    public static final BlockPistonExtension PISTON_HEAD;
    public static final WrapperBlock WOOL;
    public static final BlockPistonMoving PISTON_EXTENSION;
    public static final BlockFlower YELLOW_FLOWER;
    public static final BlockFlower RED_FLOWER;
    public static final BlockBush BROWN_MUSHROOM;
    public static final BlockBush RED_MUSHROOM;
    public static final WrapperBlock GOLD_WRAPPER_BLOCK;
    public static final WrapperBlock IRON_WRAPPER_BLOCK;
    public static final BlockSlab DOUBLE_STONE_SLAB;
    public static final BlockSlab STONE_SLAB;
    public static final WrapperBlock BRICK_WRAPPER_BLOCK;
    public static final WrapperBlock TNT;
    public static final WrapperBlock BOOKSHELF;
    public static final WrapperBlock MOSSY_COBBLESTONE;
    public static final WrapperBlock OBSIDIAN;
    public static final WrapperBlock TORCH;
    public static final BlockFire FIRE;
    public static final WrapperBlock MOB_SPAWNER;
    public static final WrapperBlock OAK_STAIRS;
    public static final BlockChest CHEST;
    public static final BlockRedstoneWire REDSTONE_WIRE;
    public static final WrapperBlock DIAMOND_ORE;
    public static final WrapperBlock DIAMOND_WRAPPER_BLOCK;
    public static final WrapperBlock CRAFTING_TABLE;
    public static final WrapperBlock WHEAT;
    public static final WrapperBlock FARMLAND;
    public static final WrapperBlock FURNACE;
    public static final WrapperBlock LIT_FURNACE;
    public static final WrapperBlock STANDING_SIGN;
    public static final BlockDoor OAK_DOOR;
    public static final BlockDoor SPRUCE_DOOR;
    public static final BlockDoor BIRCH_DOOR;
    public static final BlockDoor JUNGLE_DOOR;
    public static final BlockDoor ACACIA_DOOR;
    public static final BlockDoor DARK_OAK_DOOR;
    public static final WrapperBlock LADDER;
    public static final WrapperBlock RAIL;
    public static final WrapperBlock STONE_STAIRS;
    public static final WrapperBlock WALL_SIGN;
    public static final WrapperBlock LEVER;
    public static final WrapperBlock STONE_PRESSURE_PLATE;
    public static final BlockDoor IRON_DOOR;
    public static final WrapperBlock WOODEN_PRESSURE_PLATE;
    public static final WrapperBlock REDSTONE_ORE;
    public static final WrapperBlock LIT_REDSTONE_ORE;
    public static final WrapperBlock UNLIT_REDSTONE_TORCH;
    public static final WrapperBlock REDSTONE_TORCH;
    public static final WrapperBlock STONE_BUTTON;
    public static final WrapperBlock SNOW_LAYER;
    public static final WrapperBlock ICE;
    public static final WrapperBlock SNOW;
    public static final BlockCactus CACTUS;
    public static final WrapperBlock CLAY;
    public static final BlockReed REEDS;
    public static final WrapperBlock JUKEBOX;
    public static final WrapperBlock OAK_FENCE;
    public static final WrapperBlock SPRUCE_FENCE;
    public static final WrapperBlock BIRCH_FENCE;
    public static final WrapperBlock JUNGLE_FENCE;
    public static final WrapperBlock DARK_OAK_FENCE;
    public static final WrapperBlock ACACIA_FENCE;
    public static final WrapperBlock PUMPKIN;
    public static final WrapperBlock NETHERRACK;
    public static final WrapperBlock SOUL_SAND;
    public static final WrapperBlock GLOWSTONE;
    public static final BlockPortal PORTAL;
    public static final WrapperBlock LIT_PUMPKIN;
    public static final WrapperBlock CAKE;
    public static final BlockRedstoneRepeater UNPOWERED_REPEATER;
    public static final BlockRedstoneRepeater POWERED_REPEATER;
    public static final WrapperBlock TRAPDOOR;
    public static final WrapperBlock MONSTER_EGG;
    public static final WrapperBlock STONEBRICK;
    public static final WrapperBlock BROWN_MUSHROOM_WRAPPER_BLOCK;
    public static final WrapperBlock RED_MUSHROOM_WRAPPER_BLOCK;
    public static final WrapperBlock IRON_BARS;
    public static final WrapperBlock GLASS_PANE;
    public static final WrapperBlock MELON_WRAPPER_BLOCK;
    public static final WrapperBlock PUMPKIN_STEM;
    public static final WrapperBlock MELON_STEM;
    public static final WrapperBlock VINE;
    public static final WrapperBlock OAK_FENCE_GATE;
    public static final WrapperBlock SPRUCE_FENCE_GATE;
    public static final WrapperBlock BIRCH_FENCE_GATE;
    public static final WrapperBlock JUNGLE_FENCE_GATE;
    public static final WrapperBlock DARK_OAK_FENCE_GATE;
    public static final WrapperBlock ACACIA_FENCE_GATE;
    public static final WrapperBlock BRICK_STAIRS;
    public static final WrapperBlock STONE_BRICK_STAIRS;
    public static final BlockMycelium MYCELIUM;
    public static final WrapperBlock WATERLILY;
    public static final WrapperBlock NETHER_BRICK;
    public static final WrapperBlock NETHER_BRICK_FENCE;
    public static final WrapperBlock NETHER_BRICK_STAIRS;
    public static final WrapperBlock NETHER_WART;
    public static final WrapperBlock ENCHANTING_TABLE;
    public static final WrapperBlock BREWING_STAND;
    public static final BlockCauldron CAULDRON;
    public static final WrapperBlock END_PORTAL;
    public static final WrapperBlock END_PORTAL_FRAME;
    public static final WrapperBlock END_STONE;
    public static final WrapperBlock DRAGON_EGG;
    public static final WrapperBlock REDSTONE_LAMP;
    public static final WrapperBlock LIT_REDSTONE_LAMP;
    public static final BlockSlab DOUBLE_WOODEN_SLAB;
    public static final BlockSlab WOODEN_SLAB;
    public static final WrapperBlock COCOA;
    public static final WrapperBlock SANDSTONE_STAIRS;
    public static final WrapperBlock EMERALD_ORE;
    public static final WrapperBlock ENDER_CHEST;
    public static final BlockTripWireHook TRIPWIRE_HOOK;
    public static final WrapperBlock TRIPWIRE;
    public static final WrapperBlock EMERALD_WRAPPER_BLOCK;
    public static final WrapperBlock SPRUCE_STAIRS;
    public static final WrapperBlock BIRCH_STAIRS;
    public static final WrapperBlock JUNGLE_STAIRS;
    public static final WrapperBlock COMMAND_WRAPPER_BLOCK;
    public static final BlockBeacon BEACON;
    public static final WrapperBlock COBBLESTONE_WALL;
    public static final WrapperBlock FLOWER_POT;
    public static final WrapperBlock CARROTS;
    public static final WrapperBlock POTATOES;
    public static final WrapperBlock WOODEN_BUTTON;
    public static final BlockSkull SKULL;
    public static final WrapperBlock ANVIL;
    public static final WrapperBlock TRAPPED_CHEST;
    public static final WrapperBlock LIGHT_WEIGHTED_PRESSURE_PLATE;
    public static final WrapperBlock HEAVY_WEIGHTED_PRESSURE_PLATE;
    public static final BlockRedstoneComparator UNPOWERED_COMPARATOR;
    public static final BlockRedstoneComparator POWERED_COMPARATOR;
    public static final BlockDaylightDetector DAYLIGHT_DETECTOR;
    public static final BlockDaylightDetector DAYLIGHT_DETECTOR_INVERTED;
    public static final WrapperBlock REDSTONE_WRAPPER_BLOCK;
    public static final WrapperBlock QUARTZ_ORE;
    public static final BlockHopper HOPPER;
    public static final WrapperBlock QUARTZ_WRAPPER_BLOCK;
    public static final WrapperBlock QUARTZ_STAIRS;
    public static final WrapperBlock ACTIVATOR_RAIL;
    public static final WrapperBlock DROPPER;
    public static final WrapperBlock STAINED_HARDENED_CLAY;
    public static final WrapperBlock BARRIER;
    public static final WrapperBlock IRON_TRAPDOOR;
    public static final WrapperBlock HAY_WRAPPER_BLOCK;
    public static final WrapperBlock CARPET;
    public static final WrapperBlock HARDENED_CLAY;
    public static final WrapperBlock COAL_WRAPPER_BLOCK;
    public static final WrapperBlock PACKED_ICE;
    public static final WrapperBlock ACACIA_STAIRS;
    public static final WrapperBlock DARK_OAK_STAIRS;
    public static final WrapperBlock SLIME_WRAPPER_BLOCK;
    public static final BlockDoublePlant DOUBLE_PLANT;
    public static final BlockStainedGlass STAINED_GLASS;
    public static final BlockStainedGlassPane STAINED_GLASS_PANE;
    public static final WrapperBlock PRISMARINE;
    public static final WrapperBlock SEA_LANTERN;
    public static final WrapperBlock STANDING_BANNER;
    public static final WrapperBlock WALL_BANNER;
    public static final WrapperBlock RED_SANDSTONE;
    public static final WrapperBlock RED_SANDSTONE_STAIRS;
    public static final BlockSlab DOUBLE_STONE_SLAB2;
    public static final BlockSlab STONE_SLAB2;
    public static final WrapperBlock END_ROD;
    public static final WrapperBlock CHORUS_PLANT;
    public static final WrapperBlock CHORUS_FLOWER;
    public static final WrapperBlock PURPUR_WRAPPER_BLOCK;
    public static final WrapperBlock PURPUR_PILLAR;
    public static final WrapperBlock PURPUR_STAIRS;
    public static final BlockSlab PURPUR_DOUBLE_SLAB;
    public static final BlockSlab PURPUR_SLAB;
    public static final WrapperBlock END_BRICKS;
    public static final WrapperBlock BEETROOTS;
    public static final WrapperBlock GRASS_PATH;
    public static final WrapperBlock END_GATEWAY;
    public static final WrapperBlock REPEATING_COMMAND_WRAPPER_BLOCK;
    public static final WrapperBlock CHAIN_COMMAND_WRAPPER_BLOCK;
    public static final WrapperBlock FROSTED_ICE;
    public static final WrapperBlock MAGMA;
    public static final WrapperBlock NETHER_WART_WRAPPER_BLOCK;
    public static final WrapperBlock RED_NETHER_BRICK;
    public static final WrapperBlock BONE_WRAPPER_BLOCK;
    public static final WrapperBlock STRUCTURE_VOID;
    public static final WrapperBlock OBSERVER;
    public static final WrapperBlock WHITE_SHULKER_BOX;
    public static final WrapperBlock ORANGE_SHULKER_BOX;
    public static final WrapperBlock MAGENTA_SHULKER_BOX;
    public static final WrapperBlock LIGHT_BLUE_SHULKER_BOX;
    public static final WrapperBlock YELLOW_SHULKER_BOX;
    public static final WrapperBlock LIME_SHULKER_BOX;
    public static final WrapperBlock PINK_SHULKER_BOX;
    public static final WrapperBlock GRAY_SHULKER_BOX;
    public static final WrapperBlock SILVER_SHULKER_BOX;
    public static final WrapperBlock CYAN_SHULKER_BOX;
    public static final WrapperBlock PURPLE_SHULKER_BOX;
    public static final WrapperBlock BLUE_SHULKER_BOX;
    public static final WrapperBlock BROWN_SHULKER_BOX;
    public static final WrapperBlock GREEN_SHULKER_BOX;
    public static final WrapperBlock RED_SHULKER_BOX;
    public static final WrapperBlock BLACK_SHULKER_BOX;
    public static final WrapperBlock WHITE_GLAZED_TERRACOTTA;
    public static final WrapperBlock ORANGE_GLAZED_TERRACOTTA;
    public static final WrapperBlock MAGENTA_GLAZED_TERRACOTTA;
    public static final WrapperBlock LIGHT_BLUE_GLAZED_TERRACOTTA;
    public static final WrapperBlock YELLOW_GLAZED_TERRACOTTA;
    public static final WrapperBlock LIME_GLAZED_TERRACOTTA;
    public static final WrapperBlock PINK_GLAZED_TERRACOTTA;
    public static final WrapperBlock GRAY_GLAZED_TERRACOTTA;
    public static final WrapperBlock SILVER_GLAZED_TERRACOTTA;
    public static final WrapperBlock CYAN_GLAZED_TERRACOTTA;
    public static final WrapperBlock PURPLE_GLAZED_TERRACOTTA;
    public static final WrapperBlock BLUE_GLAZED_TERRACOTTA;
    public static final WrapperBlock BROWN_GLAZED_TERRACOTTA;
    public static final WrapperBlock GREEN_GLAZED_TERRACOTTA;
    public static final WrapperBlock RED_GLAZED_TERRACOTTA;
    public static final WrapperBlock BLACK_GLAZED_TERRACOTTA;
    public static final WrapperBlock CONCRETE;
    public static final WrapperBlock CONCRETE_POWDER;
    public static final WrapperBlock STRUCTURE_WRAPPER_BLOCK;

    /**
     * Returns the Block in the blockRegistry with the specified name.
     */
    @Nullable
    private static WrapperBlock getRegisteredBlock(String blockName) {
        WrapperBlock wrapperBlock = WrapperBlock.blockRegistry.getObject(new ResourceLocation(blockName));

        if (!CACHE.add(wrapperBlock)) {
            throw new IllegalStateException("Invalid Block requested: " + blockName);
        } else {
            return wrapperBlock;
        }
    }

    static {
        if (!Bootstrap.isRegistered()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        } else {
            CACHE = Sets.<WrapperBlock>newHashSet();
            AIR = (WrapperBlock) air;
            STONE = (WrapperBlock) stone;
            GRASS = (BlockGrass) getRegisteredBlock("grass");
            DIRT = getRegisteredBlock("dirt");
            COBBLESTONE = getRegisteredBlock("cobblestone");
            PLANKS = getRegisteredBlock("planks");
            SAPLING = getRegisteredBlock("sapling");
            BEDROCK = getRegisteredBlock("bedrock");
            FLOWING_WATER = (BlockDynamicLiquid) getRegisteredBlock("flowing_water");
            WATER = (BlockStaticLiquid) getRegisteredBlock("water");
            FLOWING_LAVA = (BlockDynamicLiquid) getRegisteredBlock("flowing_lava");
            LAVA = (BlockStaticLiquid) getRegisteredBlock("lava");
            SAND = (BlockSand) getRegisteredBlock("sand");
            GRAVEL = getRegisteredBlock("gravel");
            GOLD_ORE = getRegisteredBlock("gold_ore");
            IRON_ORE = getRegisteredBlock("iron_ore");
            COAL_ORE = getRegisteredBlock("coal_ore");
            LOG = getRegisteredBlock("log");
            LOG2 = getRegisteredBlock("log2");
            LEAVES = (BlockLeaves) getRegisteredBlock("leaves");
            LEAVES2 = (BlockLeaves) getRegisteredBlock("leaves2");
            SPONGE = getRegisteredBlock("sponge");
            GLASS = getRegisteredBlock("glass");
            LAPIS_ORE = getRegisteredBlock("lapis_ore");
            LAPIS_WRAPPER_BLOCK = getRegisteredBlock("lapis_block");
            DISPENSER = getRegisteredBlock("dispenser");
            SANDSTONE = getRegisteredBlock("sandstone");
            NOTEBLOCK = getRegisteredBlock("noteblock");
            BED = getRegisteredBlock("bed");
            GOLDEN_RAIL = getRegisteredBlock("golden_rail");
            DETECTOR_RAIL = getRegisteredBlock("detector_rail");
            STICKY_PISTON = (BlockPistonBase) getRegisteredBlock("sticky_piston");
            WEB = getRegisteredBlock("web");
            TALLGRASS = (BlockTallGrass) getRegisteredBlock("tallgrass");
            DEADBUSH = (BlockDeadBush) getRegisteredBlock("deadbush");
            PISTON = (BlockPistonBase) getRegisteredBlock("piston");
            PISTON_HEAD = (BlockPistonExtension) getRegisteredBlock("piston_head");
            WOOL = getRegisteredBlock("wool");
            PISTON_EXTENSION = (BlockPistonMoving) getRegisteredBlock("piston_extension");
            YELLOW_FLOWER = (BlockFlower) getRegisteredBlock("yellow_flower");
            RED_FLOWER = (BlockFlower) getRegisteredBlock("red_flower");
            BROWN_MUSHROOM = (BlockBush) getRegisteredBlock("brown_mushroom");
            RED_MUSHROOM = (BlockBush) getRegisteredBlock("red_mushroom");
            GOLD_WRAPPER_BLOCK = getRegisteredBlock("gold_block");
            IRON_WRAPPER_BLOCK = getRegisteredBlock("iron_block");
            DOUBLE_STONE_SLAB = (BlockSlab) getRegisteredBlock("double_stone_slab");
            STONE_SLAB = (BlockSlab) getRegisteredBlock("stone_slab");
            BRICK_WRAPPER_BLOCK = getRegisteredBlock("brick_block");
            TNT = getRegisteredBlock("tnt");
            BOOKSHELF = getRegisteredBlock("bookshelf");
            MOSSY_COBBLESTONE = getRegisteredBlock("mossy_cobblestone");
            OBSIDIAN = getRegisteredBlock("obsidian");
            TORCH = getRegisteredBlock("torch");
            FIRE = (BlockFire) getRegisteredBlock("fire");
            MOB_SPAWNER = getRegisteredBlock("mob_spawner");
            OAK_STAIRS = getRegisteredBlock("oak_stairs");
            CHEST = (BlockChest) getRegisteredBlock("chest");
            REDSTONE_WIRE = (BlockRedstoneWire) getRegisteredBlock("redstone_wire");
            DIAMOND_ORE = getRegisteredBlock("diamond_ore");
            DIAMOND_WRAPPER_BLOCK = getRegisteredBlock("diamond_block");
            CRAFTING_TABLE = getRegisteredBlock("crafting_table");
            WHEAT = getRegisteredBlock("wheat");
            FARMLAND = getRegisteredBlock("farmland");
            FURNACE = getRegisteredBlock("furnace");
            LIT_FURNACE = getRegisteredBlock("lit_furnace");
            STANDING_SIGN = getRegisteredBlock("standing_sign");
            OAK_DOOR = (BlockDoor) getRegisteredBlock("wooden_door");
            SPRUCE_DOOR = (BlockDoor) getRegisteredBlock("spruce_door");
            BIRCH_DOOR = (BlockDoor) getRegisteredBlock("birch_door");
            JUNGLE_DOOR = (BlockDoor) getRegisteredBlock("jungle_door");
            ACACIA_DOOR = (BlockDoor) getRegisteredBlock("acacia_door");
            DARK_OAK_DOOR = (BlockDoor) getRegisteredBlock("dark_oak_door");
            LADDER = getRegisteredBlock("ladder");
            RAIL = getRegisteredBlock("rail");
            STONE_STAIRS = getRegisteredBlock("stone_stairs");
            WALL_SIGN = getRegisteredBlock("wall_sign");
            LEVER = getRegisteredBlock("lever");
            STONE_PRESSURE_PLATE = getRegisteredBlock("stone_pressure_plate");
            IRON_DOOR = (BlockDoor) getRegisteredBlock("iron_door");
            WOODEN_PRESSURE_PLATE = getRegisteredBlock("wooden_pressure_plate");
            REDSTONE_ORE = getRegisteredBlock("redstone_ore");
            LIT_REDSTONE_ORE = getRegisteredBlock("lit_redstone_ore");
            UNLIT_REDSTONE_TORCH = getRegisteredBlock("unlit_redstone_torch");
            REDSTONE_TORCH = getRegisteredBlock("redstone_torch");
            STONE_BUTTON = getRegisteredBlock("stone_button");
            SNOW_LAYER = getRegisteredBlock("snow_layer");
            ICE = getRegisteredBlock("ice");
            SNOW = getRegisteredBlock("snow");
            CACTUS = (BlockCactus) getRegisteredBlock("cactus");
            CLAY = getRegisteredBlock("clay");
            REEDS = (BlockReed) getRegisteredBlock("reeds");
            JUKEBOX = getRegisteredBlock("jukebox");
            OAK_FENCE = getRegisteredBlock("fence");
            SPRUCE_FENCE = getRegisteredBlock("spruce_fence");
            BIRCH_FENCE = getRegisteredBlock("birch_fence");
            JUNGLE_FENCE = getRegisteredBlock("jungle_fence");
            DARK_OAK_FENCE = getRegisteredBlock("dark_oak_fence");
            ACACIA_FENCE = getRegisteredBlock("acacia_fence");
            PUMPKIN = getRegisteredBlock("pumpkin");
            NETHERRACK = getRegisteredBlock("netherrack");
            SOUL_SAND = getRegisteredBlock("soul_sand");
            GLOWSTONE = getRegisteredBlock("glowstone");
            PORTAL = (BlockPortal) getRegisteredBlock("portal");
            LIT_PUMPKIN = getRegisteredBlock("lit_pumpkin");
            CAKE = getRegisteredBlock("cake");
            UNPOWERED_REPEATER = (BlockRedstoneRepeater) getRegisteredBlock("unpowered_repeater");
            POWERED_REPEATER = (BlockRedstoneRepeater) getRegisteredBlock("powered_repeater");
            TRAPDOOR = getRegisteredBlock("trapdoor");
            MONSTER_EGG = getRegisteredBlock("monster_egg");
            STONEBRICK = getRegisteredBlock("stonebrick");
            BROWN_MUSHROOM_WRAPPER_BLOCK = getRegisteredBlock("brown_mushroom_block");
            RED_MUSHROOM_WRAPPER_BLOCK = getRegisteredBlock("red_mushroom_block");
            IRON_BARS = getRegisteredBlock("iron_bars");
            GLASS_PANE = getRegisteredBlock("glass_pane");
            MELON_WRAPPER_BLOCK = getRegisteredBlock("melon_block");
            PUMPKIN_STEM = getRegisteredBlock("pumpkin_stem");
            MELON_STEM = getRegisteredBlock("melon_stem");
            VINE = getRegisteredBlock("vine");
            OAK_FENCE_GATE = getRegisteredBlock("fence_gate");
            SPRUCE_FENCE_GATE = getRegisteredBlock("spruce_fence_gate");
            BIRCH_FENCE_GATE = getRegisteredBlock("birch_fence_gate");
            JUNGLE_FENCE_GATE = getRegisteredBlock("jungle_fence_gate");
            DARK_OAK_FENCE_GATE = getRegisteredBlock("dark_oak_fence_gate");
            ACACIA_FENCE_GATE = getRegisteredBlock("acacia_fence_gate");
            BRICK_STAIRS = getRegisteredBlock("brick_stairs");
            STONE_BRICK_STAIRS = getRegisteredBlock("stone_brick_stairs");
            MYCELIUM = (BlockMycelium) getRegisteredBlock("mycelium");
            WATERLILY = getRegisteredBlock("waterlily");
            NETHER_BRICK = getRegisteredBlock("nether_brick");
            NETHER_BRICK_FENCE = getRegisteredBlock("nether_brick_fence");
            NETHER_BRICK_STAIRS = getRegisteredBlock("nether_brick_stairs");
            NETHER_WART = getRegisteredBlock("nether_wart");
            ENCHANTING_TABLE = getRegisteredBlock("enchanting_table");
            BREWING_STAND = getRegisteredBlock("brewing_stand");
            CAULDRON = (BlockCauldron) getRegisteredBlock("cauldron");
            END_PORTAL = getRegisteredBlock("end_portal");
            END_PORTAL_FRAME = getRegisteredBlock("end_portal_frame");
            END_STONE = getRegisteredBlock("end_stone");
            DRAGON_EGG = getRegisteredBlock("dragon_egg");
            REDSTONE_LAMP = getRegisteredBlock("redstone_lamp");
            LIT_REDSTONE_LAMP = getRegisteredBlock("lit_redstone_lamp");
            DOUBLE_WOODEN_SLAB = (BlockSlab) getRegisteredBlock("double_wooden_slab");
            WOODEN_SLAB = (BlockSlab) getRegisteredBlock("wooden_slab");
            COCOA = getRegisteredBlock("cocoa");
            SANDSTONE_STAIRS = getRegisteredBlock("sandstone_stairs");
            EMERALD_ORE = getRegisteredBlock("emerald_ore");
            ENDER_CHEST = getRegisteredBlock("ender_chest");
            TRIPWIRE_HOOK = (BlockTripWireHook) getRegisteredBlock("tripwire_hook");
            TRIPWIRE = getRegisteredBlock("tripwire");
            EMERALD_WRAPPER_BLOCK = getRegisteredBlock("emerald_block");
            SPRUCE_STAIRS = getRegisteredBlock("spruce_stairs");
            BIRCH_STAIRS = getRegisteredBlock("birch_stairs");
            JUNGLE_STAIRS = getRegisteredBlock("jungle_stairs");
            COMMAND_WRAPPER_BLOCK = getRegisteredBlock("command_block");
            BEACON = (BlockBeacon) getRegisteredBlock("beacon");
            COBBLESTONE_WALL = getRegisteredBlock("cobblestone_wall");
            FLOWER_POT = getRegisteredBlock("flower_pot");
            CARROTS = getRegisteredBlock("carrots");
            POTATOES = getRegisteredBlock("potatoes");
            WOODEN_BUTTON = getRegisteredBlock("wooden_button");
            SKULL = (BlockSkull) getRegisteredBlock("skull");
            ANVIL = getRegisteredBlock("anvil");
            TRAPPED_CHEST = getRegisteredBlock("trapped_chest");
            LIGHT_WEIGHTED_PRESSURE_PLATE = getRegisteredBlock("light_weighted_pressure_plate");
            HEAVY_WEIGHTED_PRESSURE_PLATE = getRegisteredBlock("heavy_weighted_pressure_plate");
            UNPOWERED_COMPARATOR = (BlockRedstoneComparator) getRegisteredBlock("unpowered_comparator");
            POWERED_COMPARATOR = (BlockRedstoneComparator) getRegisteredBlock("powered_comparator");
            DAYLIGHT_DETECTOR = (BlockDaylightDetector) getRegisteredBlock("daylight_detector");
            DAYLIGHT_DETECTOR_INVERTED = (BlockDaylightDetector) getRegisteredBlock("daylight_detector_inverted");
            REDSTONE_WRAPPER_BLOCK = getRegisteredBlock("redstone_block");
            QUARTZ_ORE = getRegisteredBlock("quartz_ore");
            HOPPER = (BlockHopper) getRegisteredBlock("hopper");
            QUARTZ_WRAPPER_BLOCK = getRegisteredBlock("quartz_block");
            QUARTZ_STAIRS = getRegisteredBlock("quartz_stairs");
            ACTIVATOR_RAIL = getRegisteredBlock("activator_rail");
            DROPPER = getRegisteredBlock("dropper");
            STAINED_HARDENED_CLAY = getRegisteredBlock("stained_hardened_clay");
            BARRIER = getRegisteredBlock("barrier");
            IRON_TRAPDOOR = getRegisteredBlock("iron_trapdoor");
            HAY_WRAPPER_BLOCK = getRegisteredBlock("hay_block");
            CARPET = getRegisteredBlock("carpet");
            HARDENED_CLAY = getRegisteredBlock("hardened_clay");
            COAL_WRAPPER_BLOCK = getRegisteredBlock("coal_block");
            PACKED_ICE = getRegisteredBlock("packed_ice");
            ACACIA_STAIRS = getRegisteredBlock("acacia_stairs");
            DARK_OAK_STAIRS = getRegisteredBlock("dark_oak_stairs");
            SLIME_WRAPPER_BLOCK = getRegisteredBlock("slime");
            DOUBLE_PLANT = (BlockDoublePlant) getRegisteredBlock("double_plant");
            STAINED_GLASS = (BlockStainedGlass) getRegisteredBlock("stained_glass");
            STAINED_GLASS_PANE = (BlockStainedGlassPane) getRegisteredBlock("stained_glass_pane");
            PRISMARINE = getRegisteredBlock("prismarine");
            SEA_LANTERN = getRegisteredBlock("sea_lantern");
            STANDING_BANNER = getRegisteredBlock("standing_banner");
            WALL_BANNER = getRegisteredBlock("wall_banner");
            RED_SANDSTONE = getRegisteredBlock("red_sandstone");
            RED_SANDSTONE_STAIRS = getRegisteredBlock("red_sandstone_stairs");
            DOUBLE_STONE_SLAB2 = (BlockSlab) getRegisteredBlock("double_stone_slab2");
            STONE_SLAB2 = (BlockSlab) getRegisteredBlock("stone_slab2");
            END_ROD = getRegisteredBlock("end_rod");
            CHORUS_PLANT = getRegisteredBlock("chorus_plant");
            CHORUS_FLOWER = getRegisteredBlock("chorus_flower");
            PURPUR_WRAPPER_BLOCK = getRegisteredBlock("purpur_block");
            PURPUR_PILLAR = getRegisteredBlock("purpur_pillar");
            PURPUR_STAIRS = getRegisteredBlock("purpur_stairs");
            PURPUR_DOUBLE_SLAB = (BlockSlab) getRegisteredBlock("purpur_double_slab");
            PURPUR_SLAB = (BlockSlab) getRegisteredBlock("purpur_slab");
            END_BRICKS = getRegisteredBlock("end_bricks");
            BEETROOTS = getRegisteredBlock("beetroots");
            GRASS_PATH = getRegisteredBlock("grass_path");
            END_GATEWAY = getRegisteredBlock("end_gateway");
            REPEATING_COMMAND_WRAPPER_BLOCK = getRegisteredBlock("repeating_command_block");
            CHAIN_COMMAND_WRAPPER_BLOCK = getRegisteredBlock("chain_command_block");
            FROSTED_ICE = getRegisteredBlock("frosted_ice");
            MAGMA = getRegisteredBlock("magma");
            NETHER_WART_WRAPPER_BLOCK = getRegisteredBlock("nether_wart_block");
            RED_NETHER_BRICK = getRegisteredBlock("red_nether_brick");
            BONE_WRAPPER_BLOCK = getRegisteredBlock("bone_block");
            STRUCTURE_VOID = getRegisteredBlock("structure_void");
            OBSERVER = getRegisteredBlock("observer");
            WHITE_SHULKER_BOX = getRegisteredBlock("white_shulker_box");
            ORANGE_SHULKER_BOX = getRegisteredBlock("orange_shulker_box");
            MAGENTA_SHULKER_BOX = getRegisteredBlock("magenta_shulker_box");
            LIGHT_BLUE_SHULKER_BOX = getRegisteredBlock("light_blue_shulker_box");
            YELLOW_SHULKER_BOX = getRegisteredBlock("yellow_shulker_box");
            LIME_SHULKER_BOX = getRegisteredBlock("lime_shulker_box");
            PINK_SHULKER_BOX = getRegisteredBlock("pink_shulker_box");
            GRAY_SHULKER_BOX = getRegisteredBlock("gray_shulker_box");
            SILVER_SHULKER_BOX = getRegisteredBlock("silver_shulker_box");
            CYAN_SHULKER_BOX = getRegisteredBlock("cyan_shulker_box");
            PURPLE_SHULKER_BOX = getRegisteredBlock("purple_shulker_box");
            BLUE_SHULKER_BOX = getRegisteredBlock("blue_shulker_box");
            BROWN_SHULKER_BOX = getRegisteredBlock("brown_shulker_box");
            GREEN_SHULKER_BOX = getRegisteredBlock("green_shulker_box");
            RED_SHULKER_BOX = getRegisteredBlock("red_shulker_box");
            BLACK_SHULKER_BOX = getRegisteredBlock("black_shulker_box");
            WHITE_GLAZED_TERRACOTTA = getRegisteredBlock("white_glazed_terracotta");
            ORANGE_GLAZED_TERRACOTTA = getRegisteredBlock("orange_glazed_terracotta");
            MAGENTA_GLAZED_TERRACOTTA = getRegisteredBlock("magenta_glazed_terracotta");
            LIGHT_BLUE_GLAZED_TERRACOTTA = getRegisteredBlock("light_blue_glazed_terracotta");
            YELLOW_GLAZED_TERRACOTTA = getRegisteredBlock("yellow_glazed_terracotta");
            LIME_GLAZED_TERRACOTTA = getRegisteredBlock("lime_glazed_terracotta");
            PINK_GLAZED_TERRACOTTA = getRegisteredBlock("pink_glazed_terracotta");
            GRAY_GLAZED_TERRACOTTA = getRegisteredBlock("gray_glazed_terracotta");
            SILVER_GLAZED_TERRACOTTA = getRegisteredBlock("silver_glazed_terracotta");
            CYAN_GLAZED_TERRACOTTA = getRegisteredBlock("cyan_glazed_terracotta");
            PURPLE_GLAZED_TERRACOTTA = getRegisteredBlock("purple_glazed_terracotta");
            BLUE_GLAZED_TERRACOTTA = getRegisteredBlock("blue_glazed_terracotta");
            BROWN_GLAZED_TERRACOTTA = getRegisteredBlock("brown_glazed_terracotta");
            GREEN_GLAZED_TERRACOTTA = getRegisteredBlock("green_glazed_terracotta");
            RED_GLAZED_TERRACOTTA = getRegisteredBlock("red_glazed_terracotta");
            BLACK_GLAZED_TERRACOTTA = getRegisteredBlock("black_glazed_terracotta");
            CONCRETE = getRegisteredBlock("concrete");
            CONCRETE_POWDER = getRegisteredBlock("concrete_powder");
            STRUCTURE_WRAPPER_BLOCK = getRegisteredBlock("structure_block");
            CACHE.clear();
        }
    }
}
