package shordinger.ModWrapper.migration.wrapper.minecraft.init;

import net.minecraft.init.Items;
import net.minecraft.util.ResourceLocation;
import shordinger.ModWrapper.migration.wrapper.minecraft.item.WrapperItem;
import shordinger.ModWrapper.migration.wrapper.minecraft.item.WrapperItemArmor;

public class WrapperItems extends Items {

    public static final WrapperItem AIR;
    public static final WrapperItem IRON_SHOVEL;
    public static final WrapperItem IRON_PICKAXE;
    public static final WrapperItem IRON_AXE;
    public static final WrapperItem FLINT_AND_STEEL;
    public static final WrapperItem APPLE;
    public static final ItemBow BOW;
    public static final WrapperItem ARROW;
    public static final WrapperItem SPECTRAL_ARROW;
    public static final WrapperItem TIPPED_ARROW;
    public static final WrapperItem COAL;
    public static final WrapperItem DIAMOND;
    public static final WrapperItem IRON_INGOT;
    public static final WrapperItem GOLD_INGOT;
    public static final WrapperItem IRON_SWORD;
    public static final WrapperItem WOODEN_SWORD;
    public static final WrapperItem WOODEN_SHOVEL;
    public static final WrapperItem WOODEN_PICKAXE;
    public static final WrapperItem WOODEN_AXE;
    public static final WrapperItem STONE_SWORD;
    public static final WrapperItem STONE_SHOVEL;
    public static final WrapperItem STONE_PICKAXE;
    public static final WrapperItem STONE_AXE;
    public static final WrapperItem DIAMOND_SWORD;
    public static final WrapperItem DIAMOND_SHOVEL;
    public static final WrapperItem DIAMOND_PICKAXE;
    public static final WrapperItem DIAMOND_AXE;
    public static final WrapperItem STICK;
    public static final WrapperItem BOWL;
    public static final WrapperItem MUSHROOM_STEW;
    public static final WrapperItem GOLDEN_SWORD;
    public static final WrapperItem GOLDEN_SHOVEL;
    public static final WrapperItem GOLDEN_PICKAXE;
    public static final WrapperItem GOLDEN_AXE;
    public static final WrapperItem STRING;
    public static final WrapperItem FEATHER;
    public static final WrapperItem GUNPOWDER;
    public static final WrapperItem WOODEN_HOE;
    public static final WrapperItem STONE_HOE;
    public static final WrapperItem IRON_HOE;
    public static final WrapperItem DIAMOND_HOE;
    public static final WrapperItem GOLDEN_HOE;
    public static final WrapperItem WHEAT_SEEDS;
    public static final WrapperItem WHEAT;
    public static final WrapperItem BREAD;
    public static final WrapperItemArmor LEATHER_HELMET;
    public static final WrapperItemArmor LEATHER_CHESTPLATE;
    public static final WrapperItemArmor LEATHER_LEGGINGS;
    public static final WrapperItemArmor LEATHER_BOOTS;
    public static final WrapperItemArmor CHAINMAIL_HELMET;
    public static final WrapperItemArmor CHAINMAIL_CHESTPLATE;
    public static final WrapperItemArmor CHAINMAIL_LEGGINGS;
    public static final WrapperItemArmor CHAINMAIL_BOOTS;
    public static final WrapperItemArmor IRON_HELMET;
    public static final WrapperItemArmor IRON_CHESTPLATE;
    public static final WrapperItemArmor IRON_LEGGINGS;
    public static final WrapperItemArmor IRON_BOOTS;
    public static final WrapperItemArmor DIAMOND_HELMET;
    public static final WrapperItemArmor DIAMOND_CHESTPLATE;
    public static final WrapperItemArmor DIAMOND_LEGGINGS;
    public static final WrapperItemArmor DIAMOND_BOOTS;
    public static final WrapperItemArmor GOLDEN_HELMET;
    public static final WrapperItemArmor GOLDEN_CHESTPLATE;
    public static final WrapperItemArmor GOLDEN_LEGGINGS;
    public static final WrapperItemArmor GOLDEN_BOOTS;
    public static final WrapperItem FLINT;
    public static final WrapperItem PORKCHOP;
    public static final WrapperItem COOKED_PORKCHOP;
    public static final WrapperItem PAINTING;
    public static final WrapperItem GOLDEN_APPLE;
    public static final WrapperItem SIGN;
    public static final WrapperItem OAK_DOOR;
    public static final WrapperItem SPRUCE_DOOR;
    public static final WrapperItem BIRCH_DOOR;
    public static final WrapperItem JUNGLE_DOOR;
    public static final WrapperItem ACACIA_DOOR;
    public static final WrapperItem DARK_OAK_DOOR;
    public static final WrapperItem BUCKET;
    public static final WrapperItem WATER_BUCKET;
    public static final WrapperItem LAVA_BUCKET;
    public static final WrapperItem MINECART;
    public static final WrapperItem SADDLE;
    public static final WrapperItem IRON_DOOR;
    public static final WrapperItem REDSTONE;
    public static final WrapperItem SNOWBALL;
    public static final WrapperItem BOAT;
    public static final WrapperItem SPRUCE_BOAT;
    public static final WrapperItem BIRCH_BOAT;
    public static final WrapperItem JUNGLE_BOAT;
    public static final WrapperItem ACACIA_BOAT;
    public static final WrapperItem DARK_OAK_BOAT;
    public static final WrapperItem LEATHER;
    public static final WrapperItem MILK_BUCKET;
    public static final WrapperItem BRICK;
    public static final WrapperItem CLAY_BALL;
    public static final WrapperItem REEDS;
    public static final WrapperItem PAPER;
    public static final WrapperItem BOOK;
    public static final WrapperItem SLIME_BALL;
    public static final WrapperItem CHEST_MINECART;
    public static final WrapperItem FURNACE_MINECART;
    public static final WrapperItem EGG;
    public static final WrapperItem COMPASS;
    public static final ItemFishingRod FISHING_ROD;
    public static final WrapperItem CLOCK;
    public static final WrapperItem GLOWSTONE_DUST;
    public static final WrapperItem FISH;
    public static final WrapperItem COOKED_FISH;
    public static final WrapperItem DYE;
    public static final WrapperItem BONE;
    public static final WrapperItem SUGAR;
    public static final WrapperItem CAKE;
    public static final WrapperItem BED;
    public static final WrapperItem REPEATER;
    public static final WrapperItem COOKIE;
    public static final ItemMap FILLED_MAP;
    public static final ItemShears SHEARS;
    public static final WrapperItem MELON;
    public static final WrapperItem PUMPKIN_SEEDS;
    public static final WrapperItem MELON_SEEDS;
    public static final WrapperItem BEEF;
    public static final WrapperItem COOKED_BEEF;
    public static final WrapperItem CHICKEN;
    public static final WrapperItem COOKED_CHICKEN;
    public static final WrapperItem MUTTON;
    public static final WrapperItem COOKED_MUTTON;
    public static final WrapperItem RABBIT;
    public static final WrapperItem COOKED_RABBIT;
    public static final WrapperItem RABBIT_STEW;
    public static final WrapperItem RABBIT_FOOT;
    public static final WrapperItem RABBIT_HIDE;
    public static final WrapperItem ROTTEN_FLESH;
    public static final WrapperItem ENDER_PEARL;
    public static final WrapperItem BLAZE_ROD;
    public static final WrapperItem GHAST_TEAR;
    public static final WrapperItem GOLD_NUGGET;
    public static final WrapperItem NETHER_WART;
    public static final ItemPotion POTIONITEM;
    public static final ItemPotion SPLASH_POTION;
    public static final ItemPotion LINGERING_POTION;
    public static final WrapperItem GLASS_BOTTLE;
    public static final WrapperItem DRAGON_BREATH;
    public static final WrapperItem SPIDER_EYE;
    public static final WrapperItem FERMENTED_SPIDER_EYE;
    public static final WrapperItem BLAZE_POWDER;
    public static final WrapperItem MAGMA_CREAM;
    public static final WrapperItem BREWING_STAND;
    public static final WrapperItem CAULDRON;
    public static final WrapperItem ENDER_EYE;
    public static final WrapperItem SPECKLED_MELON;
    public static final WrapperItem SPAWN_EGG;
    public static final WrapperItem EXPERIENCE_BOTTLE;
    public static final WrapperItem FIRE_CHARGE;
    public static final WrapperItem WRITABLE_BOOK;
    public static final WrapperItem WRITTEN_BOOK;
    public static final WrapperItem EMERALD;
    public static final WrapperItem ITEM_FRAME;
    public static final WrapperItem FLOWER_POT;
    public static final WrapperItem CARROT;
    public static final WrapperItem POTATO;
    public static final WrapperItem BAKED_POTATO;
    public static final WrapperItem POISONOUS_POTATO;
    public static final ItemEmptyMap MAP;
    public static final WrapperItem GOLDEN_CARROT;
    public static final WrapperItem SKULL;
    public static final WrapperItem CARROT_ON_A_STICK;
    public static final WrapperItem NETHER_STAR;
    public static final WrapperItem PUMPKIN_PIE;
    public static final WrapperItem FIREWORKS;
    public static final WrapperItem FIREWORK_CHARGE;
    public static final WrapperItem ENCHANTED_BOOK;
    public static final WrapperItem COMPARATOR;
    public static final WrapperItem NETHERBRICK;
    public static final WrapperItem QUARTZ;
    public static final WrapperItem TNT_MINECART;
    public static final WrapperItem HOPPER_MINECART;
    public static final Wrapper WrapperItemArmor
    Stand ARMOR_STAND;
    public static final WrapperItem IRON_HORSE_ARMOR;
    public static final WrapperItem GOLDEN_HORSE_ARMOR;
    public static final WrapperItem DIAMOND_HORSE_ARMOR;
    public static final WrapperItem LEAD;
    public static final WrapperItem NAME_TAG;
    public static final WrapperItem COMMAND_BLOCK_MINECART;
    public static final WrapperItem RECORD_13;
    public static final WrapperItem RECORD_CAT;
    public static final WrapperItem RECORD_BLOCKS;
    public static final WrapperItem RECORD_CHIRP;
    public static final WrapperItem RECORD_FAR;
    public static final WrapperItem RECORD_MALL;
    public static final WrapperItem RECORD_MELLOHI;
    public static final WrapperItem RECORD_STAL;
    public static final WrapperItem RECORD_STRAD;
    public static final WrapperItem RECORD_WARD;
    public static final WrapperItem RECORD_11;
    public static final WrapperItem RECORD_WAIT;
    public static final WrapperItem PRISMARINE_SHARD;
    public static final WrapperItem PRISMARINE_CRYSTALS;
    public static final WrapperItem BANNER;
    public static final WrapperItem END_CRYSTAL;
    public static final WrapperItem SHIELD;
    public static final WrapperItem ELYTRA;
    public static final WrapperItem CHORUS_FRUIT;
    public static final WrapperItem CHORUS_FRUIT_POPPED;
    public static final WrapperItem BEETROOT_SEEDS;
    public static final WrapperItem BEETROOT;
    public static final WrapperItem BEETROOT_SOUP;
    public static final WrapperItem TOTEM_OF_UNDYING;
    public static final WrapperItem SHULKER_SHELL;
    public static final WrapperItem IRON_NUGGET;
    public static final WrapperItem KNOWLEDGE_BOOK;

    private static WrapperItem getRegisteredItem(String name) {
        WrapperItem item = WrapperItem.REGISTRY.getObject(new ResourceLocation(name));

        if (item == null) {
            throw new IllegalStateException("Invalid WrapperItem requested: " + name);
        } else {
            return item;
        }
    }

    static {
        if (!Bootstrap.isRegistered()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        } else {
            AIR = getRegisteredItem("air");
            IRON_SHOVEL = getRegisteredItem("iron_shovel");
            IRON_PICKAXE = getRegisteredItem("iron_pickaxe");
            IRON_AXE = getRegisteredItem("iron_axe");
            FLINT_AND_STEEL = getRegisteredItem("flint_and_steel");
            APPLE = getRegisteredItem("apple");
            BOW = (ItemBow) getRegisteredItem("bow");
            ARROW = getRegisteredItem("arrow");
            SPECTRAL_ARROW = getRegisteredItem("spectral_arrow");
            TIPPED_ARROW = getRegisteredItem("tipped_arrow");
            COAL = getRegisteredItem("coal");
            DIAMOND = getRegisteredItem("diamond");
            IRON_INGOT = getRegisteredItem("iron_ingot");
            GOLD_INGOT = getRegisteredItem("gold_ingot");
            IRON_SWORD = getRegisteredItem("iron_sword");
            WOODEN_SWORD = getRegisteredItem("wooden_sword");
            WOODEN_SHOVEL = getRegisteredItem("wooden_shovel");
            WOODEN_PICKAXE = getRegisteredItem("wooden_pickaxe");
            WOODEN_AXE = getRegisteredItem("wooden_axe");
            STONE_SWORD = getRegisteredItem("stone_sword");
            STONE_SHOVEL = getRegisteredItem("stone_shovel");
            STONE_PICKAXE = getRegisteredItem("stone_pickaxe");
            STONE_AXE = getRegisteredItem("stone_axe");
            DIAMOND_SWORD = getRegisteredItem("diamond_sword");
            DIAMOND_SHOVEL = getRegisteredItem("diamond_shovel");
            DIAMOND_PICKAXE = getRegisteredItem("diamond_pickaxe");
            DIAMOND_AXE = getRegisteredItem("diamond_axe");
            STICK = getRegisteredItem("stick");
            BOWL = getRegisteredItem("bowl");
            MUSHROOM_STEW = getRegisteredItem("mushroom_stew");
            GOLDEN_SWORD = getRegisteredItem("golden_sword");
            GOLDEN_SHOVEL = getRegisteredItem("golden_shovel");
            GOLDEN_PICKAXE = getRegisteredItem("golden_pickaxe");
            GOLDEN_AXE = getRegisteredItem("golden_axe");
            STRING = getRegisteredItem("string");
            FEATHER = getRegisteredItem("feather");
            GUNPOWDER = getRegisteredItem("gunpowder");
            WOODEN_HOE = getRegisteredItem("wooden_hoe");
            STONE_HOE = getRegisteredItem("stone_hoe");
            IRON_HOE = getRegisteredItem("iron_hoe");
            DIAMOND_HOE = getRegisteredItem("diamond_hoe");
            GOLDEN_HOE = getRegisteredItem("golden_hoe");
            WHEAT_SEEDS = getRegisteredItem("wheat_seeds");
            WHEAT = getRegisteredItem("wheat");
            BREAD = getRegisteredItem("bread");
            LEATHER_HELMET = (WrapperItemArmor) getRegisteredItem("leather_helmet");
            LEATHER_CHESTPLATE = (WrapperItemArmor) getRegisteredItem("leather_chestplate");
            LEATHER_LEGGINGS = (WrapperItemArmor) getRegisteredItem("leather_leggings");
            LEATHER_BOOTS = (WrapperItemArmor) getRegisteredItem("leather_boots");
            CHAINMAIL_HELMET = (WrapperItemArmor) getRegisteredItem("chainmail_helmet");
            CHAINMAIL_CHESTPLATE = (WrapperItemArmor) getRegisteredItem("chainmail_chestplate");
            CHAINMAIL_LEGGINGS = (WrapperItemArmor) getRegisteredItem("chainmail_leggings");
            CHAINMAIL_BOOTS = (WrapperItemArmor) getRegisteredItem("chainmail_boots");
            IRON_HELMET = (WrapperItemArmor) getRegisteredItem("iron_helmet");
            IRON_CHESTPLATE = (WrapperItemArmor) getRegisteredItem("iron_chestplate");
            IRON_LEGGINGS = (WrapperItemArmor) getRegisteredItem("iron_leggings");
            IRON_BOOTS = (WrapperItemArmor) getRegisteredItem("iron_boots");
            DIAMOND_HELMET = (WrapperItemArmor) getRegisteredItem("diamond_helmet");
            DIAMOND_CHESTPLATE = (WrapperItemArmor) getRegisteredItem("diamond_chestplate");
            DIAMOND_LEGGINGS = (WrapperItemArmor) getRegisteredItem("diamond_leggings");
            DIAMOND_BOOTS = (WrapperItemArmor) getRegisteredItem("diamond_boots");
            GOLDEN_HELMET = (WrapperItemArmor) getRegisteredItem("golden_helmet");
            GOLDEN_CHESTPLATE = (WrapperItemArmor) getRegisteredItem("golden_chestplate");
            GOLDEN_LEGGINGS = (WrapperItemArmor) getRegisteredItem("golden_leggings");
            GOLDEN_BOOTS = (WrapperItemArmor) getRegisteredItem("golden_boots");
            FLINT = getRegisteredItem("flint");
            PORKCHOP = getRegisteredItem("porkchop");
            COOKED_PORKCHOP = getRegisteredItem("cooked_porkchop");
            PAINTING = getRegisteredItem("painting");
            GOLDEN_APPLE = getRegisteredItem("golden_apple");
            SIGN = getRegisteredItem("sign");
            OAK_DOOR = getRegisteredItem("wooden_door");
            SPRUCE_DOOR = getRegisteredItem("spruce_door");
            BIRCH_DOOR = getRegisteredItem("birch_door");
            JUNGLE_DOOR = getRegisteredItem("jungle_door");
            ACACIA_DOOR = getRegisteredItem("acacia_door");
            DARK_OAK_DOOR = getRegisteredItem("dark_oak_door");
            BUCKET = getRegisteredItem("bucket");
            WATER_BUCKET = getRegisteredItem("water_bucket");
            LAVA_BUCKET = getRegisteredItem("lava_bucket");
            MINECART = getRegisteredItem("minecart");
            SADDLE = getRegisteredItem("saddle");
            IRON_DOOR = getRegisteredItem("iron_door");
            REDSTONE = getRegisteredItem("redstone");
            SNOWBALL = getRegisteredItem("snowball");
            BOAT = getRegisteredItem("boat");
            SPRUCE_BOAT = getRegisteredItem("spruce_boat");
            BIRCH_BOAT = getRegisteredItem("birch_boat");
            JUNGLE_BOAT = getRegisteredItem("jungle_boat");
            ACACIA_BOAT = getRegisteredItem("acacia_boat");
            DARK_OAK_BOAT = getRegisteredItem("dark_oak_boat");
            LEATHER = getRegisteredItem("leather");
            MILK_BUCKET = getRegisteredItem("milk_bucket");
            BRICK = getRegisteredItem("brick");
            CLAY_BALL = getRegisteredItem("clay_ball");
            REEDS = getRegisteredItem("reeds");
            PAPER = getRegisteredItem("paper");
            BOOK = getRegisteredItem("book");
            SLIME_BALL = getRegisteredItem("slime_ball");
            CHEST_MINECART = getRegisteredItem("chest_minecart");
            FURNACE_MINECART = getRegisteredItem("furnace_minecart");
            EGG = getRegisteredItem("egg");
            COMPASS = getRegisteredItem("compass");
            FISHING_ROD = (ItemFishingRod) getRegisteredItem("fishing_rod");
            CLOCK = getRegisteredItem("clock");
            GLOWSTONE_DUST = getRegisteredItem("glowstone_dust");
            FISH = getRegisteredItem("fish");
            COOKED_FISH = getRegisteredItem("cooked_fish");
            DYE = getRegisteredItem("dye");
            BONE = getRegisteredItem("bone");
            SUGAR = getRegisteredItem("sugar");
            CAKE = getRegisteredItem("cake");
            BED = getRegisteredItem("bed");
            REPEATER = getRegisteredItem("repeater");
            COOKIE = getRegisteredItem("cookie");
            FILLED_MAP = (ItemMap) getRegisteredItem("filled_map");
            SHEARS = (ItemShears) getRegisteredItem("shears");
            MELON = getRegisteredItem("melon");
            PUMPKIN_SEEDS = getRegisteredItem("pumpkin_seeds");
            MELON_SEEDS = getRegisteredItem("melon_seeds");
            BEEF = getRegisteredItem("beef");
            COOKED_BEEF = getRegisteredItem("cooked_beef");
            CHICKEN = getRegisteredItem("chicken");
            COOKED_CHICKEN = getRegisteredItem("cooked_chicken");
            MUTTON = getRegisteredItem("mutton");
            COOKED_MUTTON = getRegisteredItem("cooked_mutton");
            RABBIT = getRegisteredItem("rabbit");
            COOKED_RABBIT = getRegisteredItem("cooked_rabbit");
            RABBIT_STEW = getRegisteredItem("rabbit_stew");
            RABBIT_FOOT = getRegisteredItem("rabbit_foot");
            RABBIT_HIDE = getRegisteredItem("rabbit_hide");
            ROTTEN_FLESH = getRegisteredItem("rotten_flesh");
            ENDER_PEARL = getRegisteredItem("ender_pearl");
            BLAZE_ROD = getRegisteredItem("blaze_rod");
            GHAST_TEAR = getRegisteredItem("ghast_tear");
            GOLD_NUGGET = getRegisteredItem("gold_nugget");
            NETHER_WART = getRegisteredItem("nether_wart");
            POTIONITEM = (ItemPotion) getRegisteredItem("potion");
            SPLASH_POTION = (ItemPotion) getRegisteredItem("splash_potion");
            LINGERING_POTION = (ItemPotion) getRegisteredItem("lingering_potion");
            GLASS_BOTTLE = getRegisteredItem("glass_bottle");
            DRAGON_BREATH = getRegisteredItem("dragon_breath");
            SPIDER_EYE = getRegisteredItem("spider_eye");
            FERMENTED_SPIDER_EYE = getRegisteredItem("fermented_spider_eye");
            BLAZE_POWDER = getRegisteredItem("blaze_powder");
            MAGMA_CREAM = getRegisteredItem("magma_cream");
            BREWING_STAND = getRegisteredItem("brewing_stand");
            CAULDRON = getRegisteredItem("cauldron");
            ENDER_EYE = getRegisteredItem("ender_eye");
            SPECKLED_MELON = getRegisteredItem("speckled_melon");
            SPAWN_EGG = getRegisteredItem("spawn_egg");
            EXPERIENCE_BOTTLE = getRegisteredItem("experience_bottle");
            FIRE_CHARGE = getRegisteredItem("fire_charge");
            WRITABLE_BOOK = getRegisteredItem("writable_book");
            WRITTEN_BOOK = getRegisteredItem("written_book");
            EMERALD = getRegisteredItem("emerald");
            ITEM_FRAME = getRegisteredItem("item_frame");
            FLOWER_POT = getRegisteredItem("flower_pot");
            CARROT = getRegisteredItem("carrot");
            POTATO = getRegisteredItem("potato");
            BAKED_POTATO = getRegisteredItem("baked_potato");
            POISONOUS_POTATO = getRegisteredItem("poisonous_potato");
            MAP = (ItemEmptyMap) getRegisteredItem("map");
            GOLDEN_CARROT = getRegisteredItem("golden_carrot");
            SKULL = getRegisteredItem("skull");
            CARROT_ON_A_STICK = getRegisteredItem("carrot_on_a_stick");
            NETHER_STAR = getRegisteredItem("nether_star");
            PUMPKIN_PIE = getRegisteredItem("pumpkin_pie");
            FIREWORKS = getRegisteredItem("fireworks");
            FIREWORK_CHARGE = getRegisteredItem("firework_charge");
            ENCHANTED_BOOK = getRegisteredItem("enchanted_book");
            COMPARATOR = getRegisteredItem("comparator");
            NETHERBRICK = getRegisteredItem("netherbrick");
            QUARTZ = getRegisteredItem("quartz");
            TNT_MINECART = getRegisteredItem("tnt_minecart");
            HOPPER_MINECART = getRegisteredItem("hopper_minecart");
            ARMOR_STAND = (WrapperItemArmor Stand)getRegisteredItem("armor_stand");
            IRON_HORSE_ARMOR = getRegisteredItem("iron_horse_armor");
            GOLDEN_HORSE_ARMOR = getRegisteredItem("golden_horse_armor");
            DIAMOND_HORSE_ARMOR = getRegisteredItem("diamond_horse_armor");
            LEAD = getRegisteredItem("lead");
            NAME_TAG = getRegisteredItem("name_tag");
            COMMAND_BLOCK_MINECART = getRegisteredItem("command_block_minecart");
            RECORD_13 = getRegisteredItem("record_13");
            RECORD_CAT = getRegisteredItem("record_cat");
            RECORD_BLOCKS = getRegisteredItem("record_blocks");
            RECORD_CHIRP = getRegisteredItem("record_chirp");
            RECORD_FAR = getRegisteredItem("record_far");
            RECORD_MALL = getRegisteredItem("record_mall");
            RECORD_MELLOHI = getRegisteredItem("record_mellohi");
            RECORD_STAL = getRegisteredItem("record_stal");
            RECORD_STRAD = getRegisteredItem("record_strad");
            RECORD_WARD = getRegisteredItem("record_ward");
            RECORD_11 = getRegisteredItem("record_11");
            RECORD_WAIT = getRegisteredItem("record_wait");
            PRISMARINE_SHARD = getRegisteredItem("prismarine_shard");
            PRISMARINE_CRYSTALS = getRegisteredItem("prismarine_crystals");
            BANNER = getRegisteredItem("banner");
            END_CRYSTAL = getRegisteredItem("end_crystal");
            SHIELD = getRegisteredItem("shield");
            ELYTRA = getRegisteredItem("elytra");
            CHORUS_FRUIT = getRegisteredItem("chorus_fruit");
            CHORUS_FRUIT_POPPED = getRegisteredItem("chorus_fruit_popped");
            BEETROOT_SEEDS = getRegisteredItem("beetroot_seeds");
            BEETROOT = getRegisteredItem("beetroot");
            BEETROOT_SOUP = getRegisteredItem("beetroot_soup");
            TOTEM_OF_UNDYING = getRegisteredItem("totem_of_undying");
            SHULKER_SHELL = getRegisteredItem("shulker_shell");
            IRON_NUGGET = getRegisteredItem("iron_nugget");
            KNOWLEDGE_BOOK = getRegisteredItem("knowledge_book");
        }
    }
}
