@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package shordinger.ModWrapper.migration.wrapper.minecraftforge.server.terminalconsole.util;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;
